<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NiTiS_NativePackage>true</NiTiS_NativePackage>
	</PropertyGroup>

	<Import Project="../../build/common.props" />

	<ItemGroup>
		<Content Include="build/**" PackagePath="build/%(RecursiveDir)%(Filename)%(Extension)" />
		<Content Include="build/**" PackagePath="buildTransitive/%(RecursiveDir)%(Filename)%(Extension)" />
		<Content Include="runtimes/**" PackagePath="runtimes/%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
</Project>