name: Test (Multiplatform)

on:
  workflow_dispatch:
  push:
    paths:
    - "src/**.cs"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Run tests
      run: |
        dotnet test
